apiVersion: v1
kind: Service
metadata:
  name: examen-service
spec:
  type: NodePort
  selector:
    app: examen-app
  ports:
    - protocol: TCP
      port: 80 # Puerto interno del Service
      targetPort: 3000 # Puerto en el contenedor
      nodePort: 30080 # Puerto Fijo en el nodo
